# Generated by Django 3.1.2 on 2020-10-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=2000)),
            ],
        ),
    ]
