# Generated by Django 3.1.2 on 2020-10-12 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoteApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
